In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv("5000tmbd.csv")
credits=pd.read_csv("5000tmdbcredit.csv")

In [3]:
merge = movies.merge(credits, on='id')
merge.shape

(4803, 23)

In [4]:
data = merge.drop(columns=['homepage', 'title_x', 'title_y', 'status','production_countries'])
data.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,tagline,vote_average,vote_count,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
import ast
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj): 
        l.append(i['name'])
    return l

In [6]:
data['genres']=data['genres'].apply(convert)
data['production_companies']=data['production_companies'].apply(convert)
data['spoken_languages']=data['spoken_languages'].apply(convert)
data['keywords']=data['keywords'].apply(convert)
data['cast']=data['cast'].apply(convert)

In [7]:
data["genre"] = [','.join(map(str, l)) for l in data['genres']]
data["casts"] = [','.join(map(str, l)) for l in data['cast']]

In [8]:
data[['actor1', 'actor2', 'actor3','actor4']] = data['casts'].str.split(',',n= 3, expand=True)
data[['genre1', 'genre2', 'genre3','genre4']] = data['genre'].str.split(',',n= 3, expand=True)
data[['year','date']] = data['release_date'].str.split('-',n= 1, expand=True)

In [9]:
data['genre2'].fillna(data['genre1'], inplace = True)
data['genre3'].fillna(data['genre1'], inplace = True)
data['genre4'].fillna(data['genre1'], inplace = True)

data['actor2'].fillna(data['actor1'], inplace = True)
data['actor3'].fillna(data['actor1'], inplace = True)
data['actor4'].fillna(data['actor1'], inplace = True)

In [10]:
data["o+g"] = data["genre1"].map(str)+ ' ' +  data["genre2"] + ' ' + data["overview"] 
data.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,...,actor2,actor3,actor4,genre1,genre2,genre3,genre4,year,date,o+g
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[Ingenious Film Partners, Twentieth Century Fo...",2009-12-10,...,Zoe Saldana,Sigourney Weaver,"Stephen Lang,Michelle Rodriguez,Giovanni Ribis...",Action,Adventure,Fantasy,Science Fiction,2009,12-10,"Action Adventure In the 22nd century, a parapl..."
1,300000000,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[Walt Disney Pictures, Jerry Bruckheimer Films...",2007-05-19,...,Orlando Bloom,Keira Knightley,"Stellan Skarsgård,Chow Yun-fat,Bill Nighy,Geof...",Adventure,Fantasy,Action,Adventure,2007,05-19,"Adventure Fantasy Captain Barbossa, long belie..."
2,245000000,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bondâ€™s past sends him...,107.376788,"[Columbia Pictures, Danjaq, B24]",2015-10-26,...,Christoph Waltz,Léa Seydoux,"Ralph Fiennes,Monica Bellucci,Ben Whishaw,Naom...",Action,Adventure,Crime,Action,2015,10-26,Action Adventure A cryptic message from Bondâ€...
3,250000000,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[Legendary Pictures, Warner Bros., DC Entertai...",2012-07-16,...,Michael Caine,Gary Oldman,"Anne Hathaway,Tom Hardy,Marion Cotillard,Josep...",Action,Crime,Drama,Thriller,2012,07-16,Action Crime Following the death of District A...
4,260000000,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,[Walt Disney Pictures],2012-03-07,...,Lynn Collins,Samantha Morton,"Willem Dafoe,Thomas Haden Church,Mark Strong,C...",Action,Adventure,Science Fiction,Action,2012,03-07,"Action Adventure John Carter is a war-weary, f..."

In [11]:
data = data.drop(columns=['cast','tagline'])
data.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,...,actor2,actor3,actor4,genre1,genre2,genre3,genre4,year,date,o+g
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[Ingenious Film Partners, Twentieth Century Fo...",2009-12-10,...,Zoe Saldana,Sigourney Weaver,"Stephen Lang,Michelle Rodriguez,Giovanni Ribis...",Action,Adventure,Fantasy,Science Fiction,2009,12-10,"Action Adventure In the 22nd century, a parapl..."
1,300000000,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[Walt Disney Pictures, Jerry Bruckheimer Films...",2007-05-19,...,Orlando Bloom,Keira Knightley,"Stellan Skarsgård,Chow Yun-fat,Bill Nighy,Geof...",Adventure,Fantasy,Action,Adventure,2007,05-19,"Adventure Fantasy Captain Barbossa, long belie..."
2,245000000,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bondâ€™s past sends him...,107.376788,"[Columbia Pictures, Danjaq, B24]",2015-10-26,...,Christoph Waltz,Léa Seydoux,"Ralph Fiennes,Monica Bellucci,Ben Whishaw,Naom...",Action,Adventure,Crime,Action,2015,10-26,Action Adventure A cryptic message from Bondâ€...
3,250000000,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[Legendary Pictures, Warner Bros., DC Entertai...",2012-07-16,...,Michael Caine,Gary Oldman,"Anne Hathaway,Tom Hardy,Marion Cotillard,Josep...",Action,Crime,Drama,Thriller,2012,07-16,Action Crime Following the death of District A...
4,260000000,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,[Walt Disney Pictures],2012-03-07,...,Lynn Collins,Samantha Morton,"Willem Dafoe,Thomas Haden Church,Mark Strong,C...",Action,Adventure,Science Fiction,Action,2012,03-07,"Action Adventure John Carter is a war-weary, f..."

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfv = TfidfVectorizer(min_df=3,  max_features=None,
            strip_accents='unicode', analyzer='word',
            ngram_range=(1, 3),
            stop_words = 'english')
            
tfv_matrix = tfv.fit_transform(data['overview'].values.astype('U'))
tfv_matrix1 = tfv.fit_transform(data['o+g'].values.astype('U'))

In [13]:
from sklearn.metrics.pairwise import sigmoid_kernel
model = sigmoid_kernel(tfv_matrix, tfv_matrix)

In [14]:
model1 = sigmoid_kernel(tfv_matrix1, tfv_matrix1)

In [15]:
data1 = pd.Series(data.index, index=data['original_title']).drop_duplicates()

Recommend on the basis of Overview

In [16]:
def recommend_overview(title, s=model):
    idx = data1[title]
    sig_scores = list(enumerate(s[idx]))
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)
    sig_scores = sig_scores[1:6]
    movie_indices = [i[0] for i in sig_scores]
    return data['original_title'].iloc[movie_indices]

In [17]:
print(recommend_overview('Transformers: Age of Extinction'))

35      Transformers: Revenge of the Fallen
111                            Transformers
2900                Space Battleship Yamato
4710             Antarctic Edge: 70Â° South
1154                   Fifty Shades of Grey
Name: original_title, dtype: object

Recommend on the basis of Overview and Genre

In [18]:
def recommend_overview_genre(title, s=model1):
    idx = data1[title]
    sig_scores = list(enumerate(s[idx]))
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)
    sig_scores = sig_scores[1:6]
    movie_indices = [i[0] for i in sig_scores]
    return data['original_title'].iloc[movie_indices]

In [19]:
print(recommend_overview_genre('Transformers: Age of Extinction'))

35     Transformers: Revenge of the Fallen
111                           Transformers
82          Dawn of the Planet of the Apes
174                    The Incredible Hulk
581                Star Trek: Insurrection
Name: original_title, dtype: object

In [20]:
new_data = data[['id','original_title']]
new_data.head()

       id                            original_title
0   19995                                    Avatar
1     285  Pirates of the Caribbean: At World's End
2  206647                                   Spectre
3   49026                     The Dark Knight Rises
4   49529                               John Carter

In [21]:
import pickle

In [22]:
pickle.dump(new_data.to_dict(),open('movies_dict.pkl','wb'))

In [23]:
pickle.dump(model,open('model.pkl','wb'))

In [24]:
pickle.dump(model1,open('model1.pkl','wb'))